# Prediction Without Pipeline 

In [182]:
import numpy as np
import pandas as pd

In [183]:
df=pd.read_csv('train.csv')

In [184]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [185]:
df.drop(columns=['PassengerId', 'Name', 'Ticket', 'Cabin'], inplace=True)

In [186]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df.drop(columns=['Survived']),df['Survived'],test_size=0.2,random_state=42)

In [187]:
X_train.head(3)

Pclass   Sex   Age  SibSp  Parch    Fare Embarked
331       1  male  45.5      0      0  28.500        S
733       2  male  23.0      0      0  13.000        S
382       3  male  32.0      0      0   7.925        S

In [188]:
df.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64

In [189]:
df.dtypes

Survived      int64
Pclass        int64
Sex          object
Age         float64
SibSp         int64
Parch         int64
Fare        float64
Embarked     object
dtype: object

In [190]:
df['Age'] = df['Age'].fillna(0).astype(int)


In [191]:
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [234]:
transformer = ColumnTransformer(transformers=[
    ('tnf1', SimpleImputer(strategy='mean'), ['Age']),  
    ('tnf2', SimpleImputer(strategy='most_frequent'), ['Embarked']),                            
    ('tnf3', OneHotEncoder(sparse_output=False, handle_unknown='ignore'), ['Sex']),
    ('tnf4', OneHotEncoder(sparse_output=False, handle_unknown='ignore'), ['Embarked'])
], remainder='passthrough')

In [235]:
ohe_embarked = OneHotEncoder(sparse_output=False,handle_unknown='ignore'),["Embarked"]

In [236]:
transformer.fit_transform(X_train).shape

(712, 12)

In [237]:
x_train_transformed=transformer.fit_transform(X_train)

In [238]:
x_train_transformed

array([[45.5, 'S', 0.0, ..., 0.0, 0.0, 28.5],
       [23.0, 'S', 0.0, ..., 0.0, 0.0, 13.0],
       [32.0, 'S', 0.0, ..., 0.0, 0.0, 7.925],
       ...,
       [41.0, 'S', 0.0, ..., 2.0, 0.0, 14.1083],
       [14.0, 'S', 1.0, ..., 1.0, 2.0, 120.0],
       [21.0, 'S', 0.0, ..., 0.0, 1.0, 77.2875]],
      shape=(712, 12), dtype=object)

In [239]:
transformer.transform(X_test).shape

(179, 12)

In [240]:
x_test_tranformed=transformer.transform(X_test)

In [241]:
x_test_tranformed

array([[29.498846153846156, 'C', 0.0, ..., 1.0, 1.0, 15.2458],
       [31.0, 'S', 0.0, ..., 0.0, 0.0, 10.5],
       [20.0, 'S', 0.0, ..., 0.0, 0.0, 7.925],
       ...,
       [38.0, 'S', 1.0, ..., 1.0, 5.0, 31.3875],
       [17.0, 'S', 1.0, ..., 0.0, 0.0, 10.5],
       [4.0, 'S', 1.0, ..., 1.0, 1.0, 16.7]],
      shape=(179, 12), dtype=object)

In [242]:
from sklearn.tree import DecisionTreeClassifier

In [227]:
clf=DecisionTreeClassifier()
clf.fit(x_train_transformed, y_train)


ValueError: could not convert string to float: 'S'

In [231]:
x_train_transformed = transformer.fit_transform(X_train)

In [232]:
x_test_tranformed

array([[29.498846153846156, 'C', 0.0, ..., 1.0, 1.0, 15.2458],
       [31.0, 'S', 0.0, ..., 0.0, 0.0, 10.5],
       [20.0, 'S', 0.0, ..., 0.0, 0.0, 7.925],
       ...,
       [38.0, 'S', 1.0, ..., 1.0, 5.0, 31.3875],
       [17.0, 'S', 1.0, ..., 0.0, 0.0, 10.5],
       [4.0, 'S', 1.0, ..., 1.0, 1.0, 16.7]],
      shape=(179, 12), dtype=object)

In [ ]:
y_pred = clf.predict(x_test_tranformed)

In [ ]:
y_pred

array([0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 1])

# With Pipeline

In [249]:
df.drop(columns=['PassengerId','Name','Ticket','Cabin'],inplace=True)

In [251]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(df.drop(columns=['Survived']),df['Survived'],test_size=0.2,random_state=42)

In [252]:
X_train.head(5)

Pclass     Sex   Age  SibSp  Parch     Fare Embarked
331       1    male  45.5      0      0  28.5000        S
733       2    male  23.0      0      0  13.0000        S
382       3    male  32.0      0      0   7.9250        S
704       3    male  26.0      1      0   7.8542        S
813       3  female   6.0      4      2  31.2750        S

In [253]:
from sklearn.compose import ColumnTransformer

In [254]:
trf1 = ColumnTransformer([
    ( 'impute_age',SimpleImputer(),[2]),
    ('impute_embraked',SimpleImputer(strategy='most_frequent'),[6])
     
],remainder='passthrough')

In [255]:
trf2 = ColumnTransformer([
    ('ohe_sex_embarked',OneHotEncoder(sparse_output=False,handle_unknown='ignore'),[1,6])
],remainder='passthrough')

In [256]:
from sklearn.preprocessing import MinMaxScaler

In [258]:
trf3=ColumnTransformer([
    ('scale',MinMaxScaler(),slice(0,8))
])

In [260]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

trf4 = SelectKBest(score_func=chi2, k=5)

In [261]:
trf5 = DecisionTreeClassifier()

In [262]:
from sklearn.pipeline import Pipeline

In [263]:
pipe = Pipeline([
    ('trf1',trf1),
    ('trf2',trf2),
    ('trf3',trf3),
    ('trf4',trf4),
    ('trf5',trf5)
])

In [264]:
pipe.fit(X_train,y_train)

Pipeline(steps=[('trf1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('impute_age', SimpleImputer(),
                                                  [2]),
                                                 ('impute_embraked',
                                                  SimpleImputer(strategy='most_frequent'),
                                                  [6])])),
                ('trf2',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('ohe_sex_embarked',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  [1, 6])])),
                ('trf3',
                 ColumnTransformer(transformers=[('scale', MinMaxScaler(),
                                                  slice(0, 8, None))])),
                ('trf4',
                 SelectKBest(k=5,
                             score_func=<function chi2 at 0x0000020A7FAA5F80>)),
                ('trf5', DecisionTreeClassifier())])

In [265]:
pipe.named_steps

{'trf1': ColumnTransformer(remainder='passthrough',
                   transformers=[('impute_age', SimpleImputer(), [2]),
                                 ('impute_embraked',
                                  SimpleImputer(strategy='most_frequent'),
                                  [6])]),
 'trf2': ColumnTransformer(remainder='passthrough',
                   transformers=[('ohe_sex_embarked',
                                  OneHotEncoder(handle_unknown='ignore',
                                                sparse_output=False),
                                  [1, 6])]),
 'trf3': ColumnTransformer(transformers=[('scale', MinMaxScaler(), slice(0, 8, None))]),
 'trf4': SelectKBest(k=5, score_func=<function chi2 at 0x0000020A7FAA5F80>),
 'trf5': DecisionTreeClassifier()}

In [268]:
y_pred=pipe.predict(X_test)

In [269]:
y_pred

array([1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 0])

In [271]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.6256983240223464

In [272]:
from sklearn.model_selection import cross_val_score
cross_val_score(pipe,X_train,y_train,cv=5,scoring='accuracy').mean()

np.float64(0.6391214419383433)